### ISSUE TITLE
How will I integrate socket.io?

### ISSUE THREAD

**Issue by delwar2016** [fullstackreact/food-lookup-demo#9]
How will I integrate socket.io?
I want to broad-cast message server from client, So what will be good solution for that?

**Comment by acco** [comment]
Hi @delwar2016,

This would involve making modifications to `Client` so that instead of making a single HTTP request we open a socket connection with a library like Socket.io. We would want to keep that connection over during the lifetime of the app. When changes are made to the search bar, we'd use the socket to send data. We would setup a listener in `FoodSearch` that would update the component with search results whenever the socket received data.

If you have any specific questions, feel free to re-open/comment. You're also welcome to fork and implement a working demo!

**Comment by delwar2016** [comment]
Hi @acco 
Thanks for response.  Yes, I will try again. And if I face any problem in that time i will mention it clearly.
